/**
 * Division Names Mapping
 *
 * Maps ISO 3166-2 codes to display names for international divisions.
 * Only includes Phase 1 priority countries.
 */

export const DIVISION_NAMES: Record<string, string> = {
  // Canada - Provinces
  'CA-ON': 'Ontario',
  'CA-QC': 'Quebec',
  'CA-BC': 'British Columbia',
  'CA-AB': 'Alberta',
  'CA-MB': 'Manitoba',
  'CA-SK': 'Saskatchewan',
  'CA-NS': 'Nova Scotia',
  'CA-NB': 'New Brunswick',
  'CA-NL': 'Newfoundland and Labrador',
  'CA-PE': 'Prince Edward Island',
  'CA-NT': 'Northwest Territories',
  'CA-YT': 'Yukon',
  'CA-NU': 'Nunavut',

  // Australia - States & Territories
  'AU-NSW': 'New South Wales',
  'AU-VIC': 'Victoria',
  'AU-QLD': 'Queensland',
  'AU-WA': 'Western Australia',
  'AU-SA': 'South Australia',
  'AU-TAS': 'Tasmania',
  'AU-ACT': 'Australian Capital Territory',
  'AU-NT': 'Northern Territory',

  // United Kingdom - Countries
  'GB-ENG': 'England',
  'GB-SCT': 'Scotland',
  'GB-WLS': 'Wales',
  'GB-NIR': 'Northern Ireland',

  // Germany - States (Länder)
  'DE-BW': 'Baden-Württemberg',
  'DE-BY': 'Bavaria',
  'DE-BE': 'Berlin',
  'DE-BB': 'Brandenburg',
  'DE-HB': 'Bremen',
  'DE-HH': 'Hamburg',
  'DE-HE': 'Hesse',
  'DE-MV': 'Mecklenburg-Vorpommern',
  'DE-NI': 'Lower Saxony',
  'DE-NW': 'North Rhine-Westphalia',
  'DE-RP': 'Rhineland-Palatinate',
  'DE-SL': 'Saarland',
  'DE-SN': 'Saxony',
  'DE-ST': 'Saxony-Anhalt',
  'DE-SH': 'Schleswig-Holstein',
  'DE-TH': 'Thuringia',

  // France - Regions
  'FR-IDF': 'Île-de-France',
  'FR-ARA': 'Auvergne-Rhône-Alpes',
  'FR-BFC': 'Bourgogne-Franche-Comté',
  'FR-BRE': 'Brittany',
  'FR-CVL': 'Centre-Val de Loire',
  'FR-COR': 'Corsica',
  'FR-GES': 'Grand Est',
  'FR-HDF': 'Hauts-de-France',
  'FR-NOR': 'Normandy',
  'FR-NAQ': 'Nouvelle-Aquitaine',
  'FR-OCC': 'Occitanie',
  'FR-PDL': 'Pays de la Loire',
  'FR-PAC': "Provence-Alpes-Côte d'Azur",

  // Italy - Regions
  'IT-21': 'Piedmont',
  'IT-23': 'Aosta Valley',
  'IT-25': 'Lombardy',
  'IT-32': 'Trentino-Alto Adige',
  'IT-34': 'Veneto',
  'IT-36': 'Friuli Venezia Giulia',
  'IT-42': 'Liguria',
  'IT-45': 'Emilia-Romagna',
  'IT-52': 'Tuscany',
  'IT-55': 'Umbria',
  'IT-57': 'Marche',
  'IT-62': 'Lazio',
  'IT-65': 'Abruzzo',
  'IT-67': 'Molise',
  'IT-72': 'Campania',
  'IT-75': 'Apulia',
  'IT-77': 'Basilicata',
  'IT-78': 'Calabria',
  'IT-82': 'Sicily',
  'IT-88': 'Sardinia',

  // Mexico - States
  'MX-AGU': 'Aguascalientes',
  'MX-BCN': 'Baja California',
  'MX-BCS': 'Baja California Sur',
  'MX-CAM': 'Campeche',
  'MX-CHP': 'Chiapas',
  'MX-CHH': 'Chihuahua',
  'MX-CMX': 'Mexico City',
  'MX-COA': 'Coahuila',
  'MX-COL': 'Colima',
  'MX-DUR': 'Durango',
  'MX-GUA': 'Guanajuato',
  'MX-GRO': 'Guerrero',
  'MX-HID': 'Hidalgo',
  'MX-JAL': 'Jalisco',
  'MX-MEX': 'México',
  'MX-MIC': 'Michoacán',
  'MX-MOR': 'Morelos',
  'MX-NAY': 'Nayarit',
  'MX-NLE': 'Nuevo León',
  'MX-OAX': 'Oaxaca',
  'MX-PUE': 'Puebla',
  'MX-QUE': 'Querétaro',
  'MX-ROO': 'Quintana Roo',
  'MX-SLP': 'San Luis Potosí',
  'MX-SIN': 'Sinaloa',
  'MX-SON': 'Sonora',
  'MX-TAB': 'Tabasco',
  'MX-TAM': 'Tamaulipas',
  'MX-TLA': 'Tlaxcala',
  'MX-VER': 'Veracruz',
  'MX-YUC': 'Yucatán',
  'MX-ZAC': 'Zacatecas',

  // Brazil - States (most populous)
  'BR-SP': 'São Paulo',
  'BR-RJ': 'Rio de Janeiro',
  'BR-MG': 'Minas Gerais',
  'BR-BA': 'Bahia',
  'BR-RS': 'Rio Grande do Sul',
  'BR-PR': 'Paraná',
  'BR-PE': 'Pernambuco',
  'BR-CE': 'Ceará',
  'BR-PA': 'Pará',
  'BR-SC': 'Santa Catarina',
  'BR-GO': 'Goiás',
  'BR-MA': 'Maranhão',
  'BR-AM': 'Amazonas',
  'BR-ES': 'Espírito Santo',
  'BR-PB': 'Paraíba',
  'BR-DF': 'Federal District',

  // India - States (most populous)
  'IN-UP': 'Uttar Pradesh',
  'IN-MH': 'Maharashtra',
  'IN-BR': 'Bihar',
  'IN-WB': 'West Bengal',
  'IN-MP': 'Madhya Pradesh',
  'IN-TN': 'Tamil Nadu',
  'IN-RJ': 'Rajasthan',
  'IN-KA': 'Karnataka',
  'IN-GJ': 'Gujarat',
  'IN-AP': 'Andhra Pradesh',
  'IN-OR': 'Odisha',
  'IN-TG': 'Telangana',
  'IN-KL': 'Kerala',
  'IN-JH': 'Jharkhand',
  'IN-AS': 'Assam',
  'IN-PB': 'Punjab',
  'IN-HR': 'Haryana',
  'IN-DL': 'Delhi',

  // Spain - Autonomous Communities
  'ES-AN': 'Andalusia',
  'ES-AR': 'Aragon',
  'ES-AS': 'Asturias',
  'ES-IB': 'Balearic Islands',
  'ES-CN': 'Canary Islands',
  'ES-CB': 'Cantabria',
  'ES-CL': 'Castile and León',
  'ES-CM': 'Castilla-La Mancha',
  'ES-CT': 'Catalonia',
  'ES-EX': 'Extremadura',
  'ES-GA': 'Galicia',
  'ES-MD': 'Madrid',
  'ES-MC': 'Murcia',
  'ES-NC': 'Navarre',
  'ES-PV': 'Basque Country',
  'ES-RI': 'La Rioja',
  'ES-VC': 'Valencia',
};

export function getDivisionName(code: string): string {
  return DIVISION_NAMES[code] || code;
}
